"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var AlcoholicDrink_1 = require("./AlcoholicDrink");
var BrazilTaxVisitor_1 = require("./BrazilTaxVisitor");
var Cigarette_1 = require("./Cigarette");
var EuaTaxVisitor_1 = require("./EuaTaxVisitor");
var Food_1 = require("./Food");
var food = new Food_1.Food(10);
var cigarette = new Cigarette_1.Cigarette(5);
var alcoholicDrink = new AlcoholicDrink_1.AlcoholicDrink(5);
var brazilTaxVisitor = new BrazilTaxVisitor_1.BrazilTaxVisitor();
var usTaxVisitor = new EuaTaxVisitor_1.EuaTaxVisitor();
var cart = [food, cigarette, alcoholicDrink];
var total = cart.reduce(function (sum, item) { return item.getPrice() + sum; }, 0);
var totalWithTaxesBrazil = cart.reduce(function (sum, item) { return item.getPriceWithTaxes(brazilTaxVisitor) + sum; }, 0);
var totalWithTaxesUS = cart.reduce(function (sum, item) { return item.getPriceWithTaxes(usTaxVisitor) + sum; }, 0);
console.log(total);
console.log(totalWithTaxesBrazil);
console.log(totalWithTaxesUS);
